name: CI

on:
  push: 
    branches: [ "feature/*" ]

defaults:
  run:
    working-directory: app

permissions:
  contents: write
  pull-requests: write

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Inicia Banco Mysql
        run: docker compose up -d mysql

#      - name: Lint
#        run: mvn -B checkstyle:check

      - name: Unit Tests
        run: mvn clean test

      - name: Coverage
        run: mvn jacoco:report
      
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Build
        run: mvn clean package -DskipTests

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/*.jar

  create_develop:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create PR to develop
        if: success()
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          gh pr create \
            --base develop \
            --head ${{ github.ref_name }} \
            --title "Auto PR: ${{ github.ref_name }} -> develop" \
            --body "PR criada automaticamente após sucesso do CI."

  create_staging:
    needs: create_develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create PR to staging
        if: success()
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          gh pr create \
            --base staging \
            --head ${{ github.ref_name }} \
            --title "Auto PR: ${{ github.ref_name }} -> staging" \
            --body "PR criada automaticamente após sucesso do CI."
