on:
  pull_request:
    branches: [ "develop" ]

jobs:  
  create:
    needs: docker
    uses: peter-evans/create-pull-request@v7
    with:
      branch: develop
      base: staging
      title: "Auto PR: develop -> staging"